What is a function transformer in ml



The function trans is a tool in sklearn, it allows us to apply a specified function to a input data . It can be useful to perform custom transformation
 of input data in ML.

takes a single arg as an input , a single function that will be applied to

In [ ]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

#create a data set
x=np.array([[1,4],[3,4]])

#define the transformaion
log_transform=FunctionTransformer(np.log1p)

#apply the transfirmation to the dataset
x_transformed = log_transform.transform(x)

#view
print(x_transformed)

[[0.69314718 1.60943791]
 [1.38629436 1.60943791]]


In [ ]:
#practical usecase

#1.Custom feature engineering

x=np.array([[1,2],[3,4]])

#define a custom feature engineering funcation
def squ(x):
  return np.hstack((x,x**2))

#create a functiontransformer to apply the custom function

custom_transformer= FunctionTransformer(squ)

#apply the transformer to input data
x_transformed=custom_transformer.transform(x)

print(x_transformed)


[[ 1  2  1  4]
 [ 3  4  9 16]]


In [ ]:
def my_scaling(x):
  return x/np.max(x)

custom_transformer=FunctionTransformer(my_scaling)
x_transformed=custom_transformer.transform(x)
print(x_transformed)



[[0.25 0.5 ]
 [0.75 1.  ]]


In [ ]:
#data cleaning

x=np.array([[1,2],[3,np.nan]])

def my_cleaning(x):
  x[np.isnan(x)]=0
  return x

custom_transformer=FunctionTransformer(my_cleaning)
x_transformed=custom_transformer.transform(x)
print(x_transformed)

[[1. 2.]
 [3. 0.]]


In [ ]:
import pandas as pd


In [ ]:
df=pd.read_csv("/content/newplacementdata - newplacementdata.csv")

In [ ]:
df.head(3)

cgpa  placement_exam_marks  placed
0  7.19                    26       1
1  7.46                    38       1
2  7.54                    40       1

In [ ]:
x=df.drop(columns=['placed'])

In [ ]:
y=df['placed']

In [ ]:
log_transform =FunctionTransformer(np.log1p)

In [ ]:
x_transformed=log_transform.transform(x)

In [ ]:
x_transformed

cgpa  placement_exam_marks
0    2.102914              3.295837
1    2.135349              3.663562
2    2.144761              3.713572
3    2.004179              2.197225
4    2.107786              2.890372
..        ...                   ...
995  2.289500              3.806662
996  2.314514              4.189655
997  1.773256              3.555348
998  2.263844              3.850148
999  1.774952              2.397895

[1000 rows x 2 columns]

In [ ]:
df=pd.read_csv("/content/insurance - insurance.csv")
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
df['charges'].dtypes

dtype('float64')

In [ ]:
x=df.drop(columns=['charges'])


In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe =OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)
x_new = ohe.fit_transform(x[['sex','smoker','region']])

In [ ]:
y=df['charges']

In [ ]:
log_transform =FunctionTransformer(np.log1p)

In [ ]:
x_transformed=log_transform.transform(x_new)

In [ ]:
x_transformed

array([[0.        , 0.69314718, 0.        , 0.        , 0.69314718],
       [0.69314718, 0.        , 0.        , 0.69314718, 0.        ],
       [0.69314718, 0.        , 0.        , 0.69314718, 0.        ],
       ...,
       [0.        , 0.        , 0.        , 0.69314718, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.69314718],
       [0.        , 0.69314718, 0.69314718, 0.        , 0.        ]])